// Contenido del plan de Dallas: mensajes (SMS, email, WhatsApp), calendario de Instagram/TikTok, guiones de Jesús y piezas.
// Actualizado el 05-10-2026. Reglas: SMS en 1 segmento GSM (≤160 con el pie, sin tildes ni emojis); emails de lunes a jueves,
// asunto ≤45 sin emojis, cuerpo de 16 a 60 palabras; fechas, nunca días de la semana; nada de "selected", "Turin",
// cupos ni urgencia inventada; precio solo en email/SMS/WhatsApp, nunca en anuncios ni posts.
const LINK = 'juventuscampsusa.com/clinics/128/Dallas';
const PIE_SMS = 'JAcademy Texts Reply STOP to END';

const M = {
  /* ───────── SMS ───────── */
  sms1: { tit: 'SMS 1 · Familias registradas sin pagar', canal: 'SMS (Vozzi)', pub: '7 familias de Dallas registradas en la plataforma que no han pagado (export del 5-oct). Se vuelve a sacar el export el mismo día y se quita a quien ya haya pagado.', cuando: 'Martes 6 de octubre, 6:00 pm hora de Dallas',
    trig: 'Identificación (le habla a su situación exacta) y riesgo reversible (ofrece ayuda, no presiona).',
    bloques: [['Texto', `[[FIRSTNAME]], your Dallas ID Camp signup (Nov 21-22) isn't finished. Need help? Reply here. ${LINK}\n${PIE_SMS}`]],
    nota: '159 caracteres con un nombre de 8 letras. 5 de estas 7 familias son contactos nuevos que llegaron por los anuncios. Las respuestas en Vozzi las atiende alguien del equipo el mismo día.' },
  sms2: { tit: 'SMS 2 · Familias que ya conocen Juventus', canal: 'SMS (Vozzi)', pub: 'Familias de Dallas que pagaron en años anteriores (307) y registros sin pago de años anteriores (315). Sin duplicados y sin quien ya pagó Dallas 2026-27.', cuando: 'Jueves 8 de octubre, 6:00 pm hora de Dallas',
    trig: 'Especificidad (fecha, hora, sede) y la novedad real de la camiseta incluida.',
    bloques: [['Texto', `Juventus ID Camp is back in Dallas! Nov 21-22, 9AM-1PM at Soccer Spectrum. Jersey incl. ${LINK}\n${PIE_SMS}`]],
    nota: '160 caracteres. Reemplaza el SMS "aviso a conocidos" del plan general de Dallas (22-oct): no se suma.' },
  sms3: { tit: 'SMS 3 · Todos los teléfonos de Dallas', canal: 'SMS (Vozzi)', pub: '1.551 teléfonos de Dallas (familias que ya fueron, registros sin pago y contactos de la zona), menos bajas y quien ya pagó.', cuando: 'Martes 3 de noviembre, 6:00 pm hora de Dallas',
    trig: 'Autoridad (coaches from Italy) y transparencia de precio: el padre sabe todo antes de hacer clic.',
    bloques: [['Texto', `Dallas: coaches from Italy, Nov 21-22 at Soccer Spectrum. Ages 6-16, $225 with jersey. ${LINK}\n${PIE_SMS}`]],
    nota: '159 caracteres. Va en noviembre y no en octubre porque octubre ya tiene 9.428 SMS planificados y el tope de Vozzi es de 10.000 al mes.' },
  sms4: { tit: 'SMS 4 · A 3 días del camp', canal: 'SMS (Vozzi)', pub: 'Familias que ya fueron, registros sin pago (de antes y de este año). Sin quien ya pagó.', cuando: 'Miércoles 18 de noviembre, 6:00 pm hora de Dallas',
    trig: 'Urgencia real: el camp es en 3 días (fecha real, sin "últimos cupos").',
    bloques: [['Texto', `[[FIRSTNAME]], in 3 days Juventus coaches from Italy are in Richardson: Nov 21-22, 9AM-1PM. ${LINK}\n${PIE_SMS}`]],
    nota: '159 caracteres.' },
  sms5: { tit: 'SMS 5 · Recordatorio a inscritos', canal: 'SMS (Vozzi)', pub: 'Solo familias inscritas y pagadas.', cuando: 'Viernes 20 de noviembre, 5:00 pm hora de Dallas',
    trig: 'Logística: reduce dudas y ausencias.',
    bloques: [['Texto', `See you tomorrow! Juventus ID Camp 9AM, Soccer Spectrum, 1251 Digital Dr, Richardson. Bring cleats, shin guards, water.\n${PIE_SMS}`]],
    nota: 'Confirmar con logística la hora de llegada (si piden llegar antes de las 9:00) antes de enviarlo.' },

  /* ───────── EMAIL ───────── */
  em1: { tit: 'Email 1 · Anuncio', canal: 'Email (Constant Contact)', pub: '1.159 correos de Dallas, menos bajas y quien ya pagó Dallas 2026-27.', cuando: 'Miércoles 7 de octubre, 10:00 am hora de Dallas',
    trig: 'Especificidad (fecha, hora, sede, edades, qué incluye) y autoridad (entrenadores de Juventus Academy desde Italia).',
    bloques: [['Asunto A', 'Juventus ID Camp is back in Dallas'], ['Asunto B (prueba A/B)', 'Dallas, Nov 21–22: train the Juventus way'], ['Preencabezado', 'Two mornings with coaches from Italy at Soccer Spectrum.'],
      ['Cuerpo', `Hi [[FIRSTNAME]],\n\nJuventus Academy coaches from Italy are coming back to Dallas for two mornings of training: November 21–22, 9 AM–1 PM, at Soccer Spectrum in Richardson.\n\nIt's for boys and girls from 6 to 16, players and goalkeepers: skill work, small-sided games and the Juventus methodology. Every player takes home the official training jersey.\n\n[ Button: See the Dallas ID Camp → ${LINK} ]`],
      ['Bloque en español (al final del mismo correo)', '¿Prefieres leerlo en español? Entrenadores de Juventus Academy desde Italia vuelven a Dallas: 21 y 22 de noviembre, de 9 AM a 1 PM, en Soccer Spectrum (Richardson). Para niños y niñas de 6 a 16 años, jugadores y porteros. La camiseta oficial de entrenamiento va incluida.']],
    nota: 'Cabecera: el póster Hero de Dallas en horizontal. Pie: Soccer Cage Events LLC, dirección postal y enlace de baja. Sale desde info@juventuscampsusa.com (dominio autenticado).' },
  em2: { tit: 'Email 2 · Qué hace su hijo en las dos mañanas', canal: 'Email (Constant Contact)', pub: 'La misma lista de Dallas, sin quien ya pagó.', cuando: 'Martes 20 de octubre, 10:00 am hora de Dallas',
    trig: 'Identificación (el padre de un niño de club) y especificidad (qué se trabaja).',
    bloques: [['Asunto', 'What your player does in 2 mornings'], ['Preencabezado', 'Nov 21–22 at Soccer Spectrum, Richardson.'],
      ['Cuerpo', `Hi [[FIRSTNAME]],\n\nIf your child plays club soccer and you've wondered how they would train in a European academy, the Dallas ID Camp is a good way to find out.\n\nIn two mornings they work on dribbling, passing, shooting and defending with Juventus Academy coaches, then use it in small-sided games. They leave with the official training jersey.\n\n[ Button: Register for Dallas → ${LINK} ]`],
      ['Bloque en español', '¿Su hijo juega en un club y se ha preguntado cómo entrenaría en una academia europea? En dos mañanas trabaja regate, pase, tiro y defensa con entrenadores de Juventus Academy, y lo aplica en partidos reducidos. Se lleva la camiseta oficial de entrenamiento.']],
    nota: 'Cabecera: GIF o foto de entrenamiento con la camiseta negra de Juventus Academy.' },
  em3: { tit: 'Email 3 · Prueba social', canal: 'Email (Constant Contact)', pub: 'La misma lista de Dallas, sin quien ya pagó.', cuando: 'Jueves 5 de noviembre, 10:00 am hora de Dallas',
    trig: 'Prueba social con cifras reales: 307 familias de la zona de Dallas que ya pagaron un camp o clínica, y 51 niños en el ID Camp de 2024.',
    bloques: [['Asunto', '300+ Dallas families have trained with us'], ['Preencabezado', 'In 2024, 51 players joined the Dallas ID Camp.'],
      ['Cuerpo', `Hi [[FIRSTNAME]],\n\nMore than 300 families from the Dallas area have already trained with Juventus Academy coaches at our camps and clinics. In 2024, 51 players joined the Dallas ID Camp.\n\nOn November 21–22 we're back at Soccer Spectrum, 9 AM–1 PM, for boys and girls 6 to 16.\n\n[ Button: Join them in Dallas → ${LINK} ]`],
      ['Bloque en español', 'Más de 300 familias del área de Dallas ya entrenaron con entrenadores de Juventus Academy. En 2024, 51 jugadores hicieron el ID Camp de Dallas. Volvemos el 21 y 22 de noviembre a Soccer Spectrum.']],
    nota: 'Cabecera: foto real del camp de Dallas de junio de 2026 (sin el coach vetado).' },
  em4: { tit: 'Email 4 · Faltan 9 días', canal: 'Email (Constant Contact)', pub: 'La misma lista de Dallas, sin quien ya pagó.', cuando: 'Jueves 12 de noviembre, 10:00 am hora de Dallas',
    trig: 'Urgencia real (días reales que faltan) y riesgo reversible (precio claro, qué incluye y "responda este correo").',
    bloques: [['Asunto', '9 days to the Dallas ID Camp'], ['Preencabezado', 'November 21–22 at Soccer Spectrum, Richardson.'],
      ['Cuerpo', `Hi [[FIRSTNAME]],\n\nThe Dallas ID Camp is 9 days away: November 21–22, 9 AM–1 PM, at Soccer Spectrum (1251 Digital Dr., Richardson).\n\nRegistration is online and takes a few minutes. It's $225 and includes the official Juventus Academy training jersey. Questions? Just reply to this email.\n\n[ Button: Register now → ${LINK} ]`],
      ['Bloque en español', 'Faltan 9 días para el ID Camp de Dallas: 21 y 22 de noviembre, de 9 AM a 1 PM, en Soccer Spectrum. La inscripción es en línea; cuesta $225 e incluye la camiseta oficial. ¿Dudas? Responda este correo.']],
    nota: 'Si existe un código de descuento real (por ejemplo, de hermanos), se agrega aquí. Si no está confirmado, no se menciona.' },
  em5: { tit: 'Email 5 · Logística a inscritos', canal: 'Email (Constant Contact)', pub: 'Solo familias inscritas y pagadas.', cuando: 'Jueves 19 de noviembre, 10:00 am hora de Dallas',
    trig: 'Riesgo reversible: el padre llega sabiendo todo.',
    bloques: [['Asunto', 'Your Dallas ID Camp: what to bring'],
      ['Cuerpo', `Hi [[FIRSTNAME]],\n\nSee you on November 21–22 at Soccer Spectrum, 1251 Digital Dr., Richardson, TX 75081.\n\nTraining runs 9 AM–1 PM both days. Please bring cleats, shin guards and a water bottle. The official training jersey is handed out at check-in.\n\nQuestions? Just reply to this email.`]],
    nota: 'Confirmar con logística: hora de llegada, dónde se hace el check-in y si la camiseta se entrega ahí.' },

  /* ───────── WHATSAPP ───────── */
  wa1: { tit: 'WhatsApp 1 · Anuncio + flyer', canal: 'Grupos de WhatsApp', pub: 'Grupos de familias de Dallas. Lo publica la persona del equipo que administra cada grupo.', cuando: 'Miércoles 7 de octubre, 7:00 pm hora de Dallas',
    trig: 'Especificidad y autoridad. En WhatsApp los emojis sí ayudan a leer.', img: 'piezas/whatsapp_flyer_dallas.jpg',
    bloques: [['Inglés', `Hi families! ⚽ The Juventus ID Camp is coming back to Dallas 🇮🇹\n\n📅 Nov 21–22 · 9 AM–1 PM\n📍 Soccer Spectrum, 1251 Digital Dr, Richardson\n👦👧 Boys & girls 6–16, players and goalkeepers\n👕 Official Juventus Academy training jersey included\n\nTwo mornings with Juventus Academy coaches from Italy.\nRegister here 👉 ${LINK}\n\nAny questions, just write me here 🙂`],
      ['Español', `¡Hola, familias! ⚽ El ID Camp de Juventus vuelve a Dallas 🇮🇹\n\n📅 21 y 22 de noviembre · 9 AM a 1 PM\n📍 Soccer Spectrum, 1251 Digital Dr, Richardson\n👦👧 Niños y niñas de 6 a 16 años, jugadores y porteros\n👕 Camiseta oficial de entrenamiento de Juventus Academy incluida\n\nDos mañanas con entrenadores de Juventus Academy desde Italia.\nInscripción 👉 ${LINK}\n\nCualquier duda, me escriben por aquí 🙂`]],
    nota: 'Se envía con el flyer de WhatsApp. En grupos de habla hispana va la versión en español.' },
  wa2: { tit: 'WhatsApp 2 · La camiseta va incluida', canal: 'Grupos de WhatsApp', pub: 'Los mismos grupos.', cuando: 'Miércoles 21 de octubre, 7:00 pm hora de Dallas', img: 'piezas/post_camiseta_incluida.jpg',
    trig: 'Especificidad: un dato nuevo y concreto.',
    bloques: [['Inglés', `Did you know? 👕 Every player at the Dallas ID Camp takes home the official Juventus Academy training jersey.\n\nNov 21–22 at Soccer Spectrum, Richardson ⚽\n👉 ${LINK}`],
      ['Español', `¿Sabían? 👕 Cada jugador del ID Camp de Dallas se lleva la camiseta oficial de entrenamiento de Juventus Academy.\n\n21 y 22 de noviembre en Soccer Spectrum, Richardson ⚽\n👉 ${LINK}`]],
    nota: 'Se envía con el post "The jersey is included".' },
  wa3: { tit: 'WhatsApp 3 · Familias de Dallas que ya vinieron', canal: 'Grupos de WhatsApp', pub: 'Los mismos grupos.', cuando: 'Miércoles 4 de noviembre, 7:00 pm hora de Dallas',
    trig: 'Prueba social con cifra real (51 niños en 2024) y contraste (entrenar como en una academia de Juventus).',
    bloques: [['Inglés', `In 2024, 51 players from the Dallas area joined our ID Camp 💪\n\nThis year: Nov 21–22, two mornings training the way Juventus academy players do, with coaches from Italy ⚽🇮🇹\n👉 ${LINK}`],
      ['Español', `En 2024, 51 jugadores del área de Dallas hicieron nuestro ID Camp 💪\n\nEste año: 21 y 22 de noviembre, dos mañanas entrenando como en las academias de Juventus, con entrenadores desde Italia ⚽🇮🇹\n👉 ${LINK}`]],
    nota: 'Se envía con una foto real del camp de Dallas de junio de 2026.' },
  wa4: { tit: 'WhatsApp 4 · Esta semana', canal: 'Grupos de WhatsApp', pub: 'Los mismos grupos.', cuando: 'Martes 17 de noviembre, 7:00 pm hora de Dallas',
    trig: 'Urgencia real: el camp es ese fin de semana.',
    bloques: [['Inglés', `This weekend! ⚽ Juventus ID Camp Dallas · Nov 21–22 · 9 AM–1 PM · Soccer Spectrum, Richardson.\n\nRegistration is online 👉 ${LINK}\nQuestions? Write me here 🙂`],
      ['Español', `¡Este fin de semana! ⚽ ID Camp de Juventus en Dallas · 21 y 22 de noviembre · 9 AM a 1 PM · Soccer Spectrum, Richardson.\n\nInscripción en línea 👉 ${LINK}\n¿Dudas? Me escriben por aquí 🙂`]],
    nota: '' },
};

/* Calendario de Instagram y TikTok (mismas piezas en las dos cuentas). Martes y jueves feed; lunes, miércoles y viernes historias. */
const CAL = [
  ['Mar 6-oct', 'Historia', 'Historia "Dallas · info" (fecha, hora, sede, edades) con sticker de enlace', 'Lista'],
  ['Jue 8-oct', 'Post + historia', 'Post "The jersey is included" + su versión en historia', 'Lista'],
  ['Vie 9-oct', 'Historia', 'Historia "Coaches from Italy"', 'Lista'],
  ['Mar 13-oct', 'Reel', 'Reel de Jesús 1 · "Lo que su hijo se lleva" (camiseta)', 'Se graba el 6-oct'],
  ['Mié 14-oct', 'Historia', 'Compartir el reel en historia, con sticker de enlace', ''],
  ['Jue 15-oct', 'Post Collab', 'Post en colaboración con Soccer Spectrum (carrusel "Dallas, junio 2026")', 'Por hacer'],
  ['Lun 19-oct', 'Historia', 'Historia "Dallas · info" (repetir)', 'Lista'],
  ['Mar 20-oct', 'Reel', 'Reel de Jesús 2 · "Dos mañanas en el ID Camp"', 'Se graba el 6-oct'],
  ['Jue 22-oct', 'Reel (prueba)', 'Reel de Jesús en español con subtítulos en inglés (prueba del idioma)', 'Se graba el 6-oct'],
  ['Mar 27-oct', 'Reel', 'Reel de Jesús 3 · "¿Mi hijo está listo?" (6 a 16 años)', 'Se graba el 6-oct'],
  ['Jue 29-oct', 'Post', 'Post "Dallas · info" en 4:5 (la historia de información adaptada al feed)', 'Por hacer'],
  ['Mar 3-nov', 'Reel', 'Reel de Jesús 4 · "Entrenar a la manera de Juventus"', 'Se graba el 6-oct'],
  ['Jue 5-nov', 'Post', 'Post "51 jugadores en 2024" con foto real del camp de Dallas', 'Por hacer'],
  ['Mar 10-nov', 'Historia', 'Historias: preguntas frecuentes (edades, porteros, qué llevar)', 'Por hacer'],
  ['Jue 12-nov', 'Reel', 'Volver a publicar el mejor reel de Jesús del mes', ''],
  ['Mar 17-nov', 'Historia', 'Historia "This weekend in Dallas"', 'Por hacer'],
  ['Sáb 21 / Dom 22-nov', 'Historias', 'Historias en vivo desde el camp (la persona del equipo en Dallas)', ''],
];

/* Guiones de reels para Jesús (grabar el 6-oct). Sirven para Instagram/TikTok y como anuncios nuevos de Dallas. */
const REELS = [
  { n: 1, tit: '"Lo que su hijo se lleva"', tipo: 'Producto (camiseta incluida)', dur: '15–20 s', trig: 'Especificidad + novedad real',
    plano: 'Jesús de frente, plano medio, sosteniendo la camiseta negra de Juventus Academy. Al final la levanta hacia la cámara.',
    en: ['HOOK (0–3 s), levantando la camiseta: "Dallas parents: this is what your kid takes home from the ID Camp."',
         'BODY (3–14 s): "The official Juventus Academy training jersey. It comes with every registration. But what really matters is what they do in it: two mornings with our coaches from Italy, the Juventus way."',
         'CTA (14–20 s): "November 21 and 22, at Soccer Spectrum in Richardson. The link to register is right here."'],
    es: ['GANCHO: "Papás de Dallas: esto es lo que su hijo se lleva del ID Camp."',
         'CUERPO: "La camiseta oficial de entrenamiento de Juventus Academy. Viene con cada inscripción. Pero lo que de verdad importa es lo que hacen con ella: dos mañanas con nuestros entrenadores de Italia, a la manera de Juventus."',
         'CIERRE: "21 y 22 de noviembre, en Soccer Spectrum, Richardson. El enlace para inscribirse está aquí."'] },
  { n: 2, tit: '"Dos mañanas en el ID Camp"', tipo: 'Explicativo (qué pasa en el camp)', dur: '20–25 s', trig: 'Especificidad + autoridad',
    plano: 'Jesús en la cancha (Soccer Spectrum si está allá; si no, cualquier cancha), caminando hacia la cámara con un balón. Intercalar 3–4 tomas de él haciendo un gesto técnico.',
    en: ['HOOK: "Here\'s exactly what your player does in two mornings at the Juventus ID Camp in Dallas."',
         'BODY: "Technique first: dribbling, passing, shooting, defending. Then small-sided games, where they use it under pressure. Same methodology as our academies, with coaches from Italy."',
         'CTA: "November 21–22, 9 to 1, Soccer Spectrum. Boys and girls, 6 to 16. Link below."'],
    es: [] },
  { n: 3, tit: '"¿Mi hijo está listo?"', tipo: 'Objeción (edad)', dur: '20 s', trig: 'Identificación: el miedo real del padre es que el entrenamiento no sea apropiado para la edad de su hijo',
    plano: 'Jesús sentado o de pie, de frente, tono tranquilo y cercano. Sin música fuerte.',
    en: ['HOOK: "Is my 7-year-old too young? Is my 15-year-old too old? Parents ask me this all the time."',
         'BODY: "The ID Camp is for boys and girls from 6 to 16, players and goalkeepers. We work by age, so a 7-year-old and a 15-year-old don\'t do the same session. Everyone trains at their level."',
         'CTA: "If your kid loves the game, they\'re ready. Dallas, November 21–22. Link below."'],
    es: ['GANCHO: "¿Mi hijo de 7 años es muy pequeño? ¿El de 15 es muy grande? Los papás me lo preguntan todo el tiempo."',
         'CUERPO: "El ID Camp es para niños y niñas de 6 a 16 años, jugadores y porteros. Trabajamos por edades: un niño de 7 y uno de 15 no hacen la misma sesión. Cada uno entrena a su nivel."',
         'CIERRE: "Si a su hijo le encanta el fútbol, está listo. Dallas, 21 y 22 de noviembre. El enlace está abajo."'],
    ojo: 'Jesús confirma antes de grabar que los grupos se arman por edad. Si no es así, se quita esa frase.' },
  { n: 4, tit: '"Entrenar a la manera de Juventus"', tipo: 'Autoridad / contraste', dur: '15–20 s', trig: 'Contraste (no es un camp de ejercicios sueltos) + autoridad',
    plano: 'Jesús en la cancha con conos detrás. Puede cerrar con un saludo a cámara.',
    en: ['HOOK: "What\'s different about training the Juventus way?"',
         'BODY: "It\'s not just drills. Every exercise has a reason: decisions, technique under pressure, and the habits of a Juventus academy player."',
         'CTA: "Come see it in Dallas, November 21 and 22. Link below."'],
    es: [] },
];
const REEL_TIPS = [
  'Celular en vertical (9:16), a la altura de los ojos, con luz de frente. Nada de contraluz.',
  'Micrófono de solapa si hay; si no, grabar cerca y en un lugar sin eco.',
  'Ropa de entrenador de Juventus. En cuadro, solo Jesús (ni niños ni el coach vetado).',
  '2 o 3 tomas de cada guion. No hace falta decirlo palabra por palabra: lo importante es el gancho en los primeros 3 segundos.',
  'Al final de cada guion, 5 segundos de silencio mirando a cámara (sirve para cortar y para la portada).',
  'Los reels 1 y 3 también en español: son la prueba del idioma (ver frente 07).',
];

/* Piezas hechas (ChatGPT + logo real). */
const PIEZAS = {
  post: { tit: 'Post · "The jersey is included" (4:5)', imgs: ['piezas/post_camiseta_incluida.jpg'], nota: 'Fotos reales del camp de Dallas con la camiseta normal de entrenamiento (negra con mangas blancas).' },
  historias: { tit: 'Historias (9:16)', imgs: ['piezas/story_info_dallas.jpg', 'piezas/story_camiseta_incluida.jpg', 'piezas/story_coaches_italia.jpg'], nota: 'El sticker de enlace va sobre la foto, sin tapar el texto. Se publican con el enlace a la página de Dallas.' },
  flyer_wa: { tit: 'Flyer de WhatsApp (4:5)', imgs: ['piezas/whatsapp_flyer_dallas.jpg'], nota: 'Sin precio en la imagen: el precio va en el texto del mensaje cuando corresponda.' },
  volante: { tit: 'Volante impreso · carta 8,5 × 11 a 300 dpi', imgs: ['piezas/volante_dallas_preview.jpg'], nota: 'Archivo para la imprenta: <a href="piezas/VOLANTE_DALLAS_carta_300dpi.pdf" target="_blank" rel="noopener">PDF carta a 300 dpi</a> (2550 × 3300 px; el PNG queda en la carpeta del proyecto). Se probó que el QR se lee incluso reducido. El QR lleva a la página de Dallas con utm_source=flyer para medir cuántas visitas llegan por los volantes.' },
};
